config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :users
  root to: "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  
  paginates_per 15
  
  enum period: [ :day, :week, :month, :year ]
  
  scope :current, -> { where("(date > ? and repeat='f') or repeat='t'", DateTime.now.to_date-1.days) }
  scope :by_user, ->(user) { where("user_id = ?", user.id) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable
  #, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :events
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:edit, :show, :update, :destroy]
  before_action :check_access!, only: [:show, :update, :edit, :destroy]
  
  def index
    @events = Event.current
    @events = @events.by_user(current_user) if params[:my] == 'true' 
    @events = @events.page(params[:page])
  end
  
  def new
    @event = Event.new
    @event.date = DateTime.now
  end
  
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to events_path
    else
      flash[:danger] = set_error(@event)
      render 'new'
    end
  end
  
  def update
    event = @event.update(event_params)
    if event
      redirect_to events_path
    else
      render edit
    end
  end
  
  def destroy
    @event.destroy
    redirect_to events_path
  end
  
  private
  
  def event_params
    params.require(:event).permit(:name, :period, :date, :repeat)
  end
  
  def check_access!
    return true if ("#{current_user.id}" == "#{@event.user_id}" and [ 'edit', 'update', 'destroy' ].include?(action_name)) or [ 'show' ].include?(action_name)
    flash[:danger] = t('.access_error')
    redirect_to events_path 
  end
  
  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_access!
  before_action :set_user, only: [:edit, :update]
  
  def update
    if @user.update(users_params)
      redirect_to events_path
    else
      flash[:danger] = @user.errors.full_messages.to_sentence
      render 'edit'
    end
  end
  
  private
  
  def users_params
    params.require(:user).permit(:email, :password, :initials)
  end
  
  def check_access!
    return true if "#{current_user.id}" == "#{params[:id]}"
    flash[:danger] = t('.access_error')
    redirect_to events_path 
  end
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", danger: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      unless message == true
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
                concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
                concat message 
              end)
      end
    end
    nil
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.haml
%tr
  %td= event.id
  - if current_user.id == event.user_id
    %td
      = link_to event.name, edit_event_path(event)
    %td
      = link_to t('.del'),
          event_path(event),
          :method => :delete, 
          :data => { :confirm => t('.confirm', name: event.name) }
  - else
    %td
      = link_to event.name, event_path(event)
    %td

app/views/events/_event_title.html.haml
%tr
  %th #
  %th
    = t('.name') 
  %th

app/views/events/_form.html.haml
= form_for @event, html: { class: 'form-horizontal', role: 'form' } do |f|
  %div.form-group
    %label.col-sm-4.control-label{ for: 'inputName' }
      = t('.name')
    %div.col-sm-8
      = f.text_field :name, autofocus: true, :class => "form-control", :id => "name", :type => "name"
  %div.form-group
    %label.col-sm-4.control-label{ for: 'inputDate' }
      = t('.date')
    %div.col-sm-8
      = f.date_field :date, autofocus: false, :class => "form-control", :id => "date", :type => "date"
  %div.form-group
    %label.col-sm-4.control-label{ for: 'inputRepeat' }
      = t('.repeat')
    %div.col-sm-8
      = check_box("event", "repeat", onclick: 'checkAll();' )
  %div.form-group
    %label.col-sm-4.control-label{  for: 'inputPeriod' }
      = t('.period')
    %div.col-sm-8
      = f.select :period, Event.periods.keys, { include_blank: false, hide_label: true, :selected => @event.period }, {:class => "form-control"}
  %div.modal-footer
    %button.btn.btn-default{ type: 'button', 'data-dismiss': 'modal' }
      = link_to t('.close'), root_path
    - if action_name != 'show'
      %button.btn.btn-primary{ type: 'button submit' }
        = t('.submit')
:javascript
  function checkAll() {
    if ($("#event_repeat")[0].checked) {
      $("#event_period").parent().parent().show();
    } else {
      $("#event_period").parent().parent().hide();
    }
  }
  function formShow() {
    $("#name").attr('readonly', true);
    $("#date").attr('readonly', true);
    $("#event_repeat").attr('readonly', true);
    $("#event_period").attr('readonly', true); 
  }
  checkAll();
  
  
- if action_name == 'show'
  :javascript
    formShow()

app/views/events/edit.html.haml
= render 'form'

app/views/events/index.html.haml
%h1 
  = t('.title') 
  (
  = link_to t('.new'), 
            new_event_path,
            title: t('.new_event')
  )
%br
%table.table.table-striped
  %thead
    = render 'event_title'
  %tbody.tbody-event
    = render @events

%br

= paginate @events, :theme => 'twitter-bootstrap-3',
                   :pagination_class => "pagination-sm"

%br

app/views/events/new.html.haml
= render 'form'

app/views/events/show.html.haml
= render 'form'

app/views/layouts/_alert.html.haml
= flash_messages

app/views/layouts/_menu.html.haml
%nav{ class: 'navbar navbar-default navbar-fixed-top', role: 'navigation' }
  %div{ class: 'navbar-header'}
    %button.some{ type: 'button', class: 'navbar-toggle', 'data-toggle': 'collapse', 'data-target': '#bs-example-navbar-collapse-1' }
      %span{ class: 'sr-only' } Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand.some{ href: root_path } 
      Test 2
  %div{ class: 'collapse navbar-collapse', id: 'bs-example-navbar-collapse-1'}
    %ul.some{ class: 'nav navbar-nav'}
      %li.MyEvents
        = link_to t('.my_events'), events_path + "?my=true"
      %li.Events
        = link_to t('.events'), events_path
    
    %ul{ class: 'nav navbar-nav navbar-right' }
      - if user_signed_in?
        %li.dropdown
          %a{ href: '#', class: 'dropdown-toggle', 'data-toggle': 'dropdown' }
            = current_user.initials
            %strong{ class: 'caret' }
          %ul.dropdown-menu
            %li
              = link_to t('.change_user'),
                edit_user_path(current_user)
            %li
              = link_to t('.logout'), destroy_user_session_path, method: :delete
      - else
        %li
          = link_to t('.login'), new_user_session_path

app/views/layouts/application.html.haml
%html
  %head
    %title GenbankStaffTested
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    
  %body 

    %div.container-fluid
      %br
      %br
      %br
      %div.col-md-8
        = render 'layouts/menu'
        = yield
      %div.col-md-4
        = render 'layouts/alert'

app/views/users/_form.html.haml
= form_for @user, html: { class: 'form-horizontal', role: 'form' } do |f|

  %div.form-group
    %label.col-sm-4.control-label{ for: 'inputInitials' }
      = t('.initials')
    %div.col-sm-8
      = f.text_field :initials, autofocus: true, :class => 'form-control', :id => "inputInitials", :type => "initials"
  %div.form-group
    %label.col-sm-4.control-label{ for: 'inputEmail' }
      = t('.email')
    %div.col-sm-8
      = f.email_field :email, autofocus: true, :class => "form-control", :id => "inputEmai", :type => "email"
  %div.form-group
    %label.col-sm-4.control-label{ for: 'inputPassword' }
      = t('.enter_password')
    %div.col-sm-8
      = f.email_field :password, autofocus: true, :class => "form-control", :id => "inputPassword", :type => "password"
  %hr
  %div.form-group
    %label.col-sm-4.control-label{ for: 'inputStructureName' }
    %div.col-sm-8
      %button.btn.btn-default{ type: 'button', 'data-dismiss': 'modal' }
        = link_to t('.close'), root_path
      - if action_name != 'show'
        %button.btn.btn-primary{ type: 'button submit' }
          = t('.submit')

app/views/users/edit.html.haml
= render 'users/form'